# Generated by Django 4.2.7 on 2023-11-23 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateTimeField(blank=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('purpose', models.CharField(choices=[('R', 'Return'), ('E', 'Exchange'), ('O', 'Place Order')], max_length=3)),
                ('materials', models.CharField(choices=[('C', 'Chart Paper'), ('F', 'Files'), ('P', 'Pencil'), ('N', 'Notebook'), ('PN', 'Pen'), ('E', 'Exam Papers')], max_length=150)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.courses')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.departments')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.departments'),
        ),
    ]
