# Generated by Django 4.2.7 on 2023-11-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='dob',
            field=models.DateField(),
        ),
    ]
