# Generated by Django 4.2.7 on 2023-11-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_alter_registeration_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='materials',
            field=models.BooleanField(blank=True, max_length=150),
        ),
    ]
